Fix incorrect styling when <select> element is present
ckeditor/ckeditor4 pull request #4205
Opened 2020-08-14 15:46 UTC by Comandeer

## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [x] Unit tests
- [x] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [x] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
* [#4141](https://github.com/ckeditor/ckeditor4/issues/4141): Fixed: styles are incorrectly applied when there is `<select>` element inside the editor.
```

## What changes did you make?

I've added skipping for `select` and `option` elements – this way these elements are not put inside `span`s with styles.

The issue was connected with the fact that our style engine iterated through `select` and its `option`s, trying to add styling to them. This resulted in incorrect selection, jumping outside the paragraph with `select`. Skipping `select` & `option` altogether eliminates the issue.

## Which issues does your PR resolve?

Closes #4141.

2020-08-19 08:08 UTC, jacekbogdanski requested changes
Looks to work correctly.

I'm wondering if we could make this change less coupled with the `style.js` module. `style.js` already exposes `data-nostyle` attribute which probably could be used on a form elements. Could you check if we are able to use that attribute instead?

If it's not possible, maybe we could go with some more orthogonal approach by exposing API for ignoring chosen elements?

2020-08-19 08:24 UTC, Comandeer commented on tests/core/style/manual/selectfontstyles.html
> +	<h4 style="font-size:40px;font-family:arial,sans-serif;">Heading</h4>
TBH I wouldn't touch it. Selection of form elements is broken in some way in de facto every browser and I'm for replacing them with fake objects (just like we do for `iframe`s and other "weird" things).

2020-08-19 09:12 UTC, Comandeer commented
I went with simpler approach and move the array of unstylable elements to `CKEDITOR.style` property – thanks to that it's configurable now.

2020-08-19 09:15 UTC, Comandeer commented on tests/core/style/manual/selectfontstyles.html
> +	<h4 style="font-size:40px;font-family:arial,sans-serif;">Heading</h4>
I created an issue for it – #4211.

2020-08-20 23:12 UTC, hub33k commented on tests/core/style/applyremove.js
> +			if ( options.ignore && options.ignore ) {
```suggestion
			if ( options.ignore ) {
```

2020-08-24 10:38 UTC, Comandeer commented
I introduced some changes after F2F conversation with @jacekbogdanski and moved marking `select, option` as ignored to `forms` plugin.

2020-08-26 06:31 UTC, jacekbogdanski approved these changes
Looks good!

2020-08-26 06:32 UTC, merged