Tests for table selection in Safari
ckeditor/ckeditor4 pull request #4308
Opened 2020-10-02 13:18 UTC by Comandeer

## What is the purpose of this pull request?

Task

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [x] Unit tests
- [x] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [x] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

Not needed

## What changes did you make?

I've ignored the unit test that fails in Safari and added a manual one to check if the upstream issue is still present.

## Which issues does your PR resolve?

Closes #4287.
Closes #4306.

2020-10-06 07:20 UTC, jacekbogdanski reviewed
Do the tests start failing from Safari 14? It seems to work when using Safari 13.1 and it's the latest version available on Browser Stack.

2020-10-06 07:39 UTC, Comandeer commented
Yes, they fail only on Safari 14.

2020-10-06 07:59 UTC, jacekbogdanski commented
Thanks, I'm removing myself from review as I don't have macOS to test it.

2020-10-07 10:49 UTC, Dumluregn requested changes
The manual test in the current form fails. I think it will be misguiding during the testing, so I'd propose to switch the `Expected` and `Unexpected` results so that test passed and additionally add the explicit note that if test is passing then the bug is still present.

The other solution is adding a note that the test should fail instead, but I'd rather go with a positive way as in the long term it should be clearer to understand.

Also manual test should be ignored on mobile (see the comment).

2020-10-07 10:49 UTC, Dumluregn commented on tests/plugins/tableselection/manual/safaritheadlastcolumn.html
> +	if ( !CKEDITOR.env.safari ) {
As there is a part of test that requires mouse, we should either ignore the whole test on mobile or add a note that the second point shouldn't be executed there.

2020-10-07 13:04 UTC, Comandeer commented
I've split the test into two: the one is for selecting the column with the button and the second one, ignored on mobile, to select with mouse.

2020-10-07 14:09 UTC, Dumluregn approved these changes
LGTM! 🎉

2020-10-07 14:11 UTC, merged