Fix Incorrect buttons labels in High Contrast mode
ckeditor/ckeditor4 pull request #4436
Opened 2020-12-14 22:10 UTC by sculpt0r

Add padding and space in text.
Space alone doesn't give any results. But it could be helpfull for screen readers.

## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [ ] Unit tests
- [ ] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [X] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
Skip
```

## What changes did you make?

*Give an overview…*

Added `padding` left for shortcut description `span` element. 
Added this in `moono`, `moono-lisa` and `kama`.

Also added an empty character before shortcut, but it doesn't give any effect.
I keep this empty character, because of conversation with @Comandeer . He says that it's better for readers - to see separate words.

## Which issues does your PR resolve?

Closes #4422.

2020-12-15 09:02 UTC, f1ames requested changes
It's a bug fix so changelog entry should not be skipped here.

> Also added an empty character before shortcut, but it doesn't give any effect.
> I keep this empty character, because of conversation with @Comandeer . He says that it's better for readers - to see separate words.

The space doesn't have any effect since it's a space on the beginning/end of an `inline-block` element and is [trimmed by the browser](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Whitespace#What_is_whitespace).

> Added `padding` left for shortcut description `span` element in High Contrast Mode.
> Added this in `moono`, `moono-lisa` and `kama`.

I'm not sure if this is the best approach for this issue since:

* There are [more skins available](https://ckeditor.com/cke4/addons/skins/all?sort_by=field_custom_downloads_value&sort_order=DESC) and it won't work for them.
* Adding spacing with padding is fine for layout purposes. Here, I have some difficulties deciding if we should treat it as layouting or just text formatting - if the later, using padding looks like not a valid approach.

Based on the above we could simply use non breaking space here (`&nbsp;`) which will be preserved and rendered correctly and also is handled same as space by screen readers AFAIR (cc @Comandeer?).

Also it could be added directly in the template (instead of `ariaShortcut` label) because it is specific for this one usage (and `ariaShortcut` could be reused somewhere else).

2020-12-15 13:15 UTC, sculpt0r commented on skins/moono-lisa/toolbar.css
> +.cke_button_label
Definitely... ;( Sorry for that.
I revert the previous proposal.

2020-12-16 09:21 UTC, sculpt0r commented
I revert a previous proposal.

I added `&nbsp;` conditionally rendered if there is a shortcut to render.

As I check with JAWS in FF - the reader doesn't read the second `span` since the button points it as `aria-describedby`.
Together with @f1ames we decide to treat this issue purely visually.
@Comandeer also will take a look - so I create a separate issue for this.

2020-12-16 10:28 UTC, f1ames requested changes
Looks good :+1: 

@sculpt0r could you add manual test here (which forces `CKEDITOR.env.hc=true` so it can be easily tested on all OSes)?

2020-12-21 09:40 UTC, sculpt0r commented
> Looks good 
> 
> @sculpt0r could you add manual test here (which forces `CKEDITOR.env.hc=true` so it can be easily tested on all OSes)?

I added the manual test `labelhc`.
Finally I was able to force HC mode, but instead of switching `CKEDITOR.env.hc` I use `CKEDITOR.env.cssClass += ' cke_hc';`

2020-12-21 12:59 UTC, f1ames approved these changes
Looks good :+1: 

---

That's interesting in fact how to force HC mode. Normally, it would be quite easy - one can listen to [`CKEDITOR.loaded` event which is fired right after HC detection logic](https://github.com/ckeditor/ckeditor4/blob/2a74bc65e23aed7b1625e4ce5a7bd99a81514db5/core/_bootstrap.js#L45) or even better - force same color for `div` borders to trick [our detection mechanism](https://github.com/ckeditor/ckeditor4/blob/2a74bc65e23aed7b1625e4ce5a7bd99a81514db5/core/_bootstrap.js#L16-L32).

However... all this logic (from `_bootstrap.js`) is done before bender loads any manual tests content - this means it's not possible to alter the above with anything placed in manual test files. And there is no other place in fact to hook into without modifying bender or CKEditor 4 files.

Still it can be done a little more elegant than it was proposed with:

```javascript
CKEDITOR.on( 'instanceCreated', function( evt ) {
	CKEDITOR.env.hc = true;
	CKEDITOR.env.cssClass += ' cke_hc';
} );
```
as this code is executed before plugins code. Also `CKEDITOR.env.hc` should be correctly overwritten because some stuff in plugins code depends on it too.

2020-12-21 13:09 UTC, merged

2020-12-21 22:52 UTC, sculpt0r commented
To be honest, I checked a few events (including `loaded`), but I made this in more 'manual' way...
Also @Comandeer mention, that it could be difficult since UI is rendered once and not refreshing anymore.

So I correct this, according to your suggestion.

Second thought: maybe it would be useful to add some graphics related events? Like: 'beforeMenuRender`, `afterMenuRender`? It could be useful to modify some styles right before render or just after it?