Fix for --!> not treated as a valid comment end tag.
ckeditor/ckeditor4 pull request #4660
Opened 2021-04-30 10:40 UTC by Comandeer

## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [x] Unit tests
- [x] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [x] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
* [#4659](https://github.com/ckeditor/ckeditor4/issues/4659): Fixed: [`CKEDITOR.htmlParser`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_htmlParser.html) does not treat `--!>` as a comment end tag.
```

## What changes did you make?

I've added one character (to be precise: one character and one quantifier) to the parser's HTML regex.

## Which issues does your PR resolve?

Closes #4659.

2021-05-05 12:18 UTC, f1ames commented
Rebased onto latest `master`.

2021-05-05 13:16 UTC, f1ames requested changes
Looking good :+1: 

However, we have some tests failing (checked both Chrome and Firefox):

![image](https://user-images.githubusercontent.com/1061942/117146330-624f1300-adb4-11eb-89da-57e75694ad9e.png)

2021-05-05 14:58 UTC, Comandeer commented on tests/core/htmlparser/comments.js
> +	bender.test( {
IMO that's enough. Such a change is not that complex after all and older tests should also cover comments with `--!>`.

2021-05-05 15:25 UTC, Comandeer commented
Ok, I've added additional test case.

2021-05-06 09:23 UTC, f1ames reviewed
Since one test suite from related tests PR fails, I will wait for the fix there and continue with the review. Overall, it's looking good :+1: 

## Code

LGTM :+1: 

## Unit test

Since this is a core change I run all tests on all desktop browsers.

*   Chrome :heavy\_check\_mark: (CI) 
*   Firefox :heavy\_check\_mark:
*   Safari :heavy\_check\_mark:
*   Edge (skipped)
*   IE11 :-1: - one test suite fails, see related tests PR 
*   IE10 (skipped for now, waiting for IE11 fix)
*   IE9 (skipped for now, waiting for IE11 fix)
*   IE8 :heavy\_check\_mark:(`is:unit,group:Security,group:Core,path:/tests/plugins/widget,path:/tests/plugins/image,path:/tests/plugins/pastefromword,group:Tickets`)
*   Chrome@Android (skipped)
*   Safari@iOS (skipped)

## Manual test

*   Chrome :heavy\_check\_mark:
*   Firefox :heavy\_check\_mark:
*   Safari :heavy\_check\_mark:
*   Edge (skipped)
*   IE11 :heavy\_check\_mark:
*   IE10 (skipped for now, waiting for IE11 fix)
*   IE9 (skipped for now, waiting for IE11 fix)
*   IE8 :heavy\_check\_mark:
*   Chrome@Android (skipped)
*   Safari@iOS (skipped)

2021-05-07 11:20 UTC, f1ames approved these changes
Ok, rechecked fix tests :+1: LGTM :tada: 

## Unit tests

*   Chrome :heavy\_check\_mark:
*   Firefox :heavy\_check\_mark:
*   IE11 :heavy\_check\_mark:
* IE10  :heavy\_check\_mark:(`is:unit,group:Security,group:Core,path:/tests/plugins/widget,path:/tests/plugins/image,path:/tests/plugins/pastefromword,group:Tickets`)
*   IE9 :heavy\_check\_mark:(`is:unit,group:Security,group:Core,path:/tests/plugins/widget,path:/tests/plugins/image,path:/tests/plugins/pastefromword,group:Tickets`)
*   IE8 :heavy\_check\_mark:

## Manual tests

*   IE10 :heavy\_check\_mark:
*   IE9 :heavy\_check\_mark:

2021-05-07 11:33 UTC, merged