Fix failing tests/core/filter/editor
ckeditor/ckeditor4 pull request #4849
Opened 2021-08-18 06:50 UTC by sculpt0r

It's no longer valid since fakeobjects plugin is using ACF

## What is the purpose of this pull request?

Failing test fix

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [ ] Unit tests
- [ ] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [X] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
skip
```

## What changes did you make?

*Give an overview…*

I removed the failing assertion. This assertion is no longer valid since `fakeobjects` plugin is using ACF. It was not possible to remove this plugin with `removePlugins` config option since this one is inlining in build process into `ckeditor` file.

There are still two assertions left that verify the usage of two filter types.

## Which issues does your PR resolve?

Closes #4821

2021-08-18 09:28 UTC, jacekbogdanski requested changes
I was rather thinking about removing Fake Objects plugin (so probably also iframe, flash, pagebreak, etc as they use it under the hood) from these specific tests, so we still keep test coverage for this particular feature. WDYT?

2021-08-23 06:04 UTC, sculpt0r commented
Rebased on the newest master

2021-08-23 07:20 UTC, sculpt0r commented
> I was rather thinking about removing Fake Objects plugin (so probably also iframe, flash, pagebreak, etc as they use it under the hood) from these specific tests, so we still keep test coverage for this particular feature. WDYT?

Unfortunately, the code from fakeobjects plugin that is executed in `afterInit` method is executed even without plugins that require this plugin (even not directly: `flash,forms,iframe,autolink,uploadfile,link,pagebreak,autoembed`) 🤔 Which looks like we add some functionality even if there is no plugin that relays on it...

2021-08-23 08:59 UTC, jacekbogdanski approved these changes

2021-08-23 08:59 UTC, merged