Fix: Pasting Outlook email with horizontal line and image
ckeditor/ckeditor4 pull request #4985
Opened 2021-11-23 06:30 UTC by KarolDawidziuk

## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [x] Unit tests
- [x] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [x] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
* [#4873](https://github.com/ckeditor/ckeditor4/issues/4873): Fixed: Pasting Outlook email with horizontal line prevents images from being uploaded.
```

## What changes did you make?

During extracting images from `rtf`, the code allowed to add an unsupported image type `image/wmf` to return images array which causes next pasting problems.

Additionally, there was a reported problem with pasting images by using one of the uploaders `CKF or EI` so to be sure that this fix works with both versions, I've prepared two manual tests to cover this case.

But I am wondering that we need an outlook to test it, but at the moment I have not found a solution that would cover this case with a unit test. 

## Which issues does your PR resolve?

Closes #4873.

2021-11-29 21:18 UTC, sculpt0r commented
Rebased on newest master

2021-12-02 10:01 UTC, jacekbogdanski requested changes

2021-12-02 13:01 UTC, KarolDawidziuk commented on plugins/pastetools/filter/image.js
> +			if ( imageType === 'image/wmf' && isHorizontalLine ) {
I thought that unit tests were falling without type checking, but I now see that everything is fine, so I removed this check.

2021-12-03 11:44 UTC, jacekbogdanski approved these changes

2021-12-03 11:44 UTC, merged