Apply extra style when the dialog tab is focused on HC mode
ckeditor/ckeditor4 pull request #5012
Opened 2022-01-03 07:36 UTC by KarolDawidziuk

## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [ ] Unit tests
- [x] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [x] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
* [#4934](https://github.com/ckeditor/ckeditor4/issues/4934): Fixed: Active focus in dialog tabs is not visible in the High Contrast mode.
```

## What changes did you make?

It's a simple change, I just set the underline for the dialog tab title when the focus is on that item.

I was wondering between `underline` and `border-style: dashed`. IMO first looks better but can be confusing with the link. If we decide that a different style would be a better solution the change will be quick 😉 

## Which issues does your PR resolve?

Closes #4934.

2022-01-04 11:02 UTC, sculpt0r requested changes
Hi @KarolDawidziuk - the underline looks good. Since the active tab is already bordered - it doesn't get too much correlation to link - IMO.

I have to ask you for separate manual tests for each skin. Please take a look at https://github.com/ckeditor/ckeditor4/tree/master/tests/plugins/balloontoolbar/manual - we have there multiple tests files for each skin. Besides that - take a look at my inline comments.

2022-01-04 11:02 UTC, sculpt0r commented on tests/plugins/dialog/manual/focusdialogtabhc.html
> +		if ( bender.tools.env.mobile || !CKEDITOR.env.hc ) {
Seems like just `.env.hc` is enough for ignoring test.
```suggestion
		if ( !CKEDITOR.env.hc ) {
```

2022-01-05 09:15 UTC, KarolDawidziuk commented on tests/plugins/dialog/manual/focusdialogtabhc.md
> +1. Set the High Contrast Mode to white.
The white mode was the last one that I tested, so I mistakenly added information about it. I deleted it. 😉

2022-01-05 09:15 UTC, KarolDawidziuk commented
Thank you @sculpt0r for the review.

I added improvements that you mentioned above and it's ready for another one

2022-01-05 13:16 UTC, sculpt0r approved these changes
Thanks for the tests for each skin. I've made a simple correction. We should explicit set skin for such test, even if it is the same as the default value :)

Anyway - I will extract an issue from this PR - because those dialogs look a little bit inconsistently (focus, active element). Some of the fields for `moono` and `moono-lisa` are invisible...

So - for this one: LGTM 🎉

2022-01-05 13:21 UTC, merged