Update license banners
ckeditor/ckeditor4 pull request #5037
Opened 2022-01-17 11:27 UTC by Comandeer

## What is the purpose of this pull request?

Task

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [ ] Unit tests
- [ ] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [ ] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

skip

## What changes did you make?

The PR contains updates of license banners in all files.

2022-01-17 12:38 UTC, Comandeer commented
I've updated the license update script to ignore git ignored files and files inside git submodules. It's helpful when running the script in other repos, e.g. `ckeditor4-docs`.

I've also added a simple `console.log()` to know which files are touched.

2022-01-24 10:38 UTC, sculpt0r requested changes
Overall looks good. However, I found a few places that should be updated. The date was updated, but due to links - they don't match to old company regexp:
![image](https://user-images.githubusercontent.com/6498567/150766024-7847328e-2b67-4aab-960f-eaedd59f8d08.png)

Due to ☝️  maybe we can just update them manually without updating the regexp? Since tif we are going to ever change the company name again - it will be a different regexp anyway.

2022-01-24 21:43 UTC, Comandeer commented
> maybe we can just update them manually without updating the regexp?

Never! I've updated the regex accordingly :stuck\_out\_tongue:I've also added `.json` files to files allowed to be updated.

2022-01-25 09:27 UTC, sculpt0r approved these changes

2022-01-25 09:28 UTC, merged