T/5044
ckeditor/ckeditor4 pull request #5047
Opened 2022-01-25 09:38 UTC by JohnRDOrazio

## What is the purpose of this pull request?

Bug fix for issue #5044 

## Does your PR contain necessary tests?

This patch contains a simple addition of CSS rules, to bring styling back to multiple select controls for when they lose focus. The browser styling is reset by the skins, so new styling needs to be reinstated for such specific cases.

### This PR contains

- [ ] Unit tests
- [ ] Manual tests
- [*] N/A
- 
## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [*] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
* [#5044](https://github.com/ckeditor/ckeditor4/issues/5044):
  * add rule for selected options of multiple selects, to skins/kama/reset.css
  * add rule for selected options of multiple selects, to skins/moono-lisa/reset.css
  * add rule for selected options of multiple selects, to skins/moono/reset.css
```

## What changes did you make?

Added rule in the stylesheets of each skin, to reinstate styling of selected options in multiple selects.

## Which issues does your PR resolve?

Closes #5044.

2022-01-25 14:06 UTC, sculpt0r commented
Thank you @JohnRDOrazio for the effort to create a fix in this PR. We will review it and provide information about the results.

2022-02-02 09:15 UTC, JohnRDOrazio commented
any way to prevent this from becoming "stale", while you are reviewing it?

2022-02-02 12:01 UTC, sculpt0r commented
I'll handle that @JohnRDOrazio  - thank you for reminder :)

2022-02-07 10:27 UTC, sculpt0r requested changes
Hi @JohnRDOrazio - your solutions is working fine 👍 

However, we need at least one manual test for each skin. Could you prepare them? Take a look at other manual tests in the project: e.g. https://github.com/ckeditor/ckeditor4/tree/master/tests/core/skin/manual

also, please take a look at our [code guide](https://github.com/ckeditor/ckeditor4/blob/master/dev/docs/codestyle.md#31-manual-tests).

2022-02-09 11:02 UTC, JohnRDOrazio commented
I'm not very familiar with bender, but I believe I have created the requested tests? Can you confirm?

2022-02-10 08:59 UTC, sculpt0r commented
Rebased onto newest master.

2022-02-10 10:12 UTC, sculpt0r requested changes
Hi @JohnRDOrazio 

Thank you for preparing the manual test - it was almost perfect ;)

I managed to shrink it a little bit: we need as small sample as possible to reproduce the issue. Less code to maintain and to read is always better. Please take a look at changes that I've made in https://github.com/ckeditor/ckeditor4/pull/5047/commits/699547287ab3d228da288c729a9b4fe3f9e19707

The previous version didn't open properly. I assume you didn't manage to run it on [bender environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html)? However, I made some changes in `moonolisamultiselect` to guide you with changes:
- in `@bender-ckeditor-plugins` tag we need `wysiwygarea` plugin to initialize the editor properly
- in `@bender-tags` - we are putting the next release version number. It changed in the meantime to `4.17.3`
- removed the dialog logic - since it requires an additional plugin. All we need is to just show the dialog. There is far less code and logic if we just show it on a button click.
- removed all additional onChange logic from the dialog, also I left only a single list. It is enough to reproduce the issue.
- things from above allows simplifying editor initialization, also I removed unnecessary config options
- we use only `var` instead of `let` and `const` because CKE4 is supporting also old browsers like IE8
- the proper value for moonolisa skin in options is `moono-lisa` (with the dash inside)
- there is no need to put body and head elements in the manual test. Also, we don't need additional CSS file in samples (could you remove it?) The fix you provide in skins reset.css files is enough

Could you:
- do the same changes for two other skin tests?
- adjust the tests steps - so they match the new scenario? Wait for the button to be active, click on it to open the dialog and all the stuff with selecting list items and focus.
- make sure the code style is following [our code style](https://github.com/ckeditor/ckeditor4/blob/master/dev/docs/codestyle.md)

2022-02-18 10:11 UTC, JohnRDOrazio commented
@sculpt0r I simplified the other two tests as asked. I have no idea how to use the bender environment, I have never used it. I made the tests simply by a bit of guesswork, looking at other examples.

I have tried to setup bender, I installed the cli globally with `npm install -g benderjs-cli` and I ran `bender init` in my ckeditor test folder, and then `bender server run`, but I'm not seeing any manual tests in this interface. What steps should I take to view the tests in a bender environment?

2022-02-18 10:21 UTC, sculpt0r commented
Hi @JohnRDOrazio,
If you are seeing the bender testing page properly, then you just need to select the correct filter:
![image](https://user-images.githubusercontent.com/6498567/154663892-2024096f-e7f2-41e9-8ee4-080e9835f668.png)

If I good understand - you managed to open such bender page?

2022-02-18 10:24 UTC, JohnRDOrazio commented
Got it! The bender page automatically had the `is:unit` filter, once I removed that I was able to see the manual tests. They all seem to be working.

2022-02-21 08:37 UTC, sculpt0r commented
Rebased onto newest master.

2022-02-21 08:49 UTC, sculpt0r approved these changes
Hi @JohnRDOrazio 

Everything looks and works properly - LGTM 🎉 

It's nice that you were able to run bender I change the rest of the tests.

Thank you for your commitment to CKE4 development! Thanks to you - there is one bug less in the editor :) I added you to the changelog :)

2022-02-21 08:50 UTC, merged