Fix removing multiple lists
ckeditor/ckeditor4 pull request #5071
Opened 2022-02-02 13:06 UTC by KarolDawidziuk

## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [x] Unit tests
- [x] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [x] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
skip
```

## What changes did you make?

After adding a fix for removing multiple lists #4943 there was a problem with removing lists where the first element of the list was not fully selected. This resulted in the entire list item being removed instead of just the selected content. 

The bugged part was in the `isFirstListItem()` function, which checked for a previous item in the list, but did not check if the entire item was selected.

I just added an additional condition in the return statement to check if all the content from the first list item was selected.

## Which issues does your PR resolve?

Closes #5068.

2022-02-03 12:23 UTC, jacekbogdanski requested changes
The issue is a bit more complicated and I can still reproduce an error when deleting the list starting at the first list item and offset 0. It looks like enlarging block elements with visible magic lines incorrectly sets up range offsets, as magicline element is available in the editor content. Once it gets hidden on `saveSnapshot` event we operate on an outdated range when deleting lists content.

I've prepared a simple fix for it by firstly checking for multiple lists case and then preparing the range for deletion (after `saveSnapshot` call). It could be also implemented by extending `magicline` plugin with an additional generic event like `hideUIView` or feature detection.

@KarolDawidziuk please take a look at my proposition (it still may require some refactoring) and fix the remaining issues in this PR.

2022-02-03 13:10 UTC, jacekbogdanski commented on core/editable.js
> +			}
This code is very unreadable. I will simplify it in the upcoming commit.

2022-02-03 14:20 UTC, KarolDawidziuk commented on tests/core/editable/manual/removealmostentileliets.md
> +All two lists have been removed.
Yes, there was a typo in the file name. I'll change that and update the description.

2022-02-03 14:21 UTC, KarolDawidziuk commented on tests/core/editable/manual/removemultiplelistunsupported.html
>  	( function() {
Yes, but I didn't want to create 4 editors in case the browser wasn't supported. So I'd like to stay with that syntax if you don't mind.

2022-02-03 14:22 UTC, KarolDawidziuk commented on tests/core/editable/manual/removemultiplelistunsupported.html
>  		if( !CKEDITOR.env.ie && !CKEDITOR.env.gecko ) {
These cases are covered in the unit tests. I didn't want to duplicate the testing process. Still, there is a manual test named `removemultiplelist` that is available in every browser.

2022-02-03 16:05 UTC, KarolDawidziuk commented
Thank you @jacekbogdanski for your improvements.

It's ready for the next one.

I have added more manual tests for removing multiple lists, including nested lists. Additionally, I've added separate manual tests for removing lists with `magicline` plugin.

2022-02-04 09:06 UTC, jacekbogdanski approved these changes
Let's make sure that everything is alright before merging this PR with @ckeditor/qa-team help. It would be good to verify these tests and play a bit with lists:
```
tests/core/editable/manual/removelistatoffset
tests/core/editable/manual/removelistswithmagicline
tests/core/editable/manual/removemultiplelists
tests/core/editable/manual/removemultiplelistswithmagicline
```

2022-02-04 10:19 UTC, Mgsy commented
It's still possible to reproduce the issue after applying a link to the text that should be removed:

```
<p>test</p>

<ol>
	<li>tes<a href="http://d">[t1</a></li>
	<li><a href="http://d">test2</a></li>
</ol>

<p><a href="http://d">test3</a></p>

<ol>
	<li><a href="http://d">test4</a></li>
	<li><a href="http://d">test5]</a></li>
</ol>
```

![](https://user-images.githubusercontent.com/20988892/152512195-0a75d565-9ee7-49db-b482-c0b33dac96f3.gif)

2022-02-04 10:27 UTC, dufipl commented
Not only a link but reproduces also when the background colour is set to deleted text:
![list remove error](https://user-images.githubusercontent.com/32898551/152513326-21051a39-e6fc-4bcd-a831-43d9811b9587.gif)

2022-02-04 11:17 UTC, Mgsy commented
We have tested it with @dufipl and after the last fix everything works as expected and we didn't notice any regression.

2022-02-04 11:20 UTC, jacekbogdanski commented
Great to hear that, thank you! We still need to add additional unit test coverage for these changes, but it shouldn't stop us from merging this PR and finishing the testing phase.

2022-02-04 11:23 UTC, jacekbogdanski approved these changes

2022-02-04 11:24 UTC, merged