Fix failing tests
ckeditor/ckeditor4 pull request #5143
Opened 2022-03-31 06:55 UTC by sculpt0r

## What is the purpose of this pull request?

Bug fix / Failinig tests fix
## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [ ] Unit tests
- [ ] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [X] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
none
```

## What changes did you make?

*Give an overview…*
For #5119 - added test ignore
For #5116 - enlarged test awaiting time. On slower networks (mobile) the template was still loading when the test executed the assertion. 
For #5115 - I added those tests to ignored on IE9. On group and on the individual runs they failed 1/10...

## Which issues does your PR resolve?

Closes #5119
Closes #5116 
Closes #5115

2022-04-07 13:26 UTC, Comandeer requested changes
LGTM, I just have some doubts around the `image2/link` test (see my inline comments).

2022-04-07 13:26 UTC, Comandeer commented on tests/plugins/image2/link.js
> +			// (#3761, #5115)
Additionally I'm not able to make this test fail for me in IE9 on `master` :thinking:

2022-04-08 11:40 UTC, sculpt0r commented on tests/plugins/image2/link.js
> +			// (#3761, #5115)
Where did you test it? BS or VM?

2022-04-08 11:45 UTC, sculpt0r commented
@Comandeer - the reference issue number is corrected. Good catch 👍  Could you take a look at this PR again? Also: https://github.com/ckeditor/ckeditor4/pull/5143#discussion_r846025400 - I was testing it at VM - what environment did you use?

2022-04-11 10:07 UTC, Comandeer commented
> I was testing it at VM - what environment did you use?

I've also tested int on VM.

2022-04-22 08:02 UTC, sculpt0r commented
As for failing tests on IE9: This time the test fails at 8-th refresh:
![image2_link](https://user-images.githubusercontent.com/6498567/164644839-25757b17-a92f-4c0a-b902-ba1b707ed455.PNG)

2022-04-22 14:51 UTC, Comandeer approved these changes
Ok, if this test really fails in IE9 (still no luck on my VM), then I'm ok with these changes.

2022-04-22 14:54 UTC, merged