Fix for unfocusable toolbar buttons in VO on iOS
ckeditor/ckeditor4 pull request #5155
Opened 2022-04-13 13:39 UTC by Comandeer

## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [x] Unit tests
- [x] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [x] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
* [#4855](https://github.com/ckeditor/ckeditor4/issues/4855): Fixed: buttons are unfocusable while using the editor with VoiceOver on iOS.
```

## What changes did you make?

I've removed the code mentioned in https://github.com/ckeditor/ckeditor4/issues/4855#issuecomment-1097851400 and checked if the issue with the focus on startup is still present in JAWS. As expected, it's no longer reproducible. Yet, to be perfectly sure, I've added the manual test for JAWS.

## Which issues does your PR resolve?

Closes #4855.

2022-04-13 15:44 UTC, Comandeer commented
I've removed that variable as it's not needed anymore. However, I'm wondering if it's not a breaking change :thinking: After all it was exposed on the editor's instance. OTOH, it's probably a private API as `editor.toolbox` is not documented at all.

2022-04-14 11:10 UTC, jacekbogdanski requested changes
I think we should be ok, I've done some quick googling including StackOverflow and I didn't notice any important references to this property. It has not been documented and should be treated as a private API, so any potential breaking changes may happen only if someone incorrectly integrated the editor.

There is one issue though, I mislook that previously thinking that again PFW tests are failing on FF, but seems like there are some new tests that are not stable after your changes:
<img width="818" alt="image" src="https://user-images.githubusercontent.com/10279586/163378183-b384d8a1-e226-4491-a307-43b2aa4946ac.png">

I can also confirm that D&D on Firefox stopped working properly:

https://user-images.githubusercontent.com/10279586/163379295-691c363e-f669-4230-ac0c-60f57fa18839.mov

Note that after D&D focus goes to the toolbar instead of the editor. It looks like the original code comment was misleading and the issue is not only related to JAWS.

2022-04-26 15:50 UTC, Comandeer commented
I've modified the hack for Firefox to move the focus to the toolbar and then back to the editor. I've also added tests for this case.

2022-04-27 13:15 UTC, jacekbogdanski approved these changes
Well, workarounds like to get out of control easily :) I didn't encounter any other issues with focus after your changes, so good job 👍🏻

2022-04-27 13:24 UTC, merged