Improve performance of editorplaceholder plugin
ckeditor/ckeditor4 pull request #5233
Opened 2022-06-07 09:58 UTC by jacekbogdanski

## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [x] Unit tests
- [ ] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [ ] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
Fixed:
* [#5184](https://github.com/ckeditor/ckeditor4/issues/5184): Fixed: [Editor Placeholder](https://ckeditor.com/cke4/addon/wysiwygarea) plugin degredates typing performance.

API changes:
* [#5184](https://github.com/ckeditor/ckeditor4/issues/5184): Added [`config.editorplaceholder_delay`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-editorplaceholder_delay) configuration option allowing to delay placeholder before it is toggled when changing editor content.
* [#5184](https://github.com/ckeditor/ckeditor4/issues/5184): Added [`CKEDITOR.tools.debounce()`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_tools.html#method-debounce) function allowing to postpone passed function execution until the given milliseconds have elapsed since the last time it was invoked
```

## What changes did you make?

Added simple debounce logic allowing to mitigate the issue with toggling editor placeholder on change event too often. I didn't add any manual tests as I don't really see any deterministic way to manually test that change, since the typing performance may be connected to a specific machine. Most likely, unit tests should be sufficient to test these changes.

## Which issues does your PR resolve?

Closes #5184

2022-06-07 14:55 UTC, jacekbogdanski commented on plugins/editorplaceholder/plugin.js
> +			bindPlaceholderEvent( editor, 'blur' );
These events are not debounced on purpose, as debounce logic on focus/blur creates a visible placeholder delay. In probably 99% of cases we could simply skip toggling editor placeholder on the `change` event as, during normal editor usage, the editor placeholder is not visible until you blur the editor. However, a `change` event is required for API manipulation like `editor.insertText`.

2022-06-13 08:13 UTC, Comandeer commented
Rebased onto latest `master`.

2022-06-13 14:30 UTC, Comandeer requested changes
WDYT about adding some manual test, e.g. an editor with a big image inside? It should allow to verify if the fix really fix the performance issue.

Additionally, we already have [`CKEDITOR.tools.buffers.throttle`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_tools_buffers_throttle.html). I'm wondering if it won't be more consistent if the newly added API was added as `CKEDITOR.tools.buffers.debounce` and has a similar shape to other `CKEDITOR.tools.buffers` members, instead of being a completely separate being.

2022-06-17 10:24 UTC, jacekbogdanski commented on plugins/editorplaceholder/plugin.js
> +		}
What is the advantage of such change? It sounds like a nitpick for me (which could even decrease readability, but that's subjective).

2022-06-17 10:46 UTC, jacekbogdanski commented
> WDYT about adding some manual test, e.g. an editor with a big image inside? It should allow to verify if the fix really fix the performance issue.

I'm a bit skeptical of that proposition because it still won't let us test these changes in a deterministic manner. Manual tests are run basically only in 2 cases:
* PR review
* Testing phase
As for PR review, I agree that adding such test could improve the overall reviewing experience, as you can just check out the old version, keep the manual test, and confirm the results. However, in the case of the testing phase, we may get many false-positive results e.g because manual tests will rely on personal tester experience (the high-resolution images will slow down the editor anyway).

I've checked how it would work with a solid base64 2.5MB image and I can admit that there is a difference in typing performance, but not that significant to differentiate it without direct comparison to code with no patch.

2022-06-17 10:54 UTC, jacekbogdanski commented
> Additionally, we already have [CKEDITOR.tools.buffers.throttle](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_tools_buffers_throttle.html). I'm wondering if it won't be more consistent if the newly added API was added as CKEDITOR.tools.buffers.debounce and has a similar shape to other CKEDITOR.tools.buffers members, instead of being a completely separate being.

While I agree that debounce somehow fits those classes, I would like to avoid such dedication to mimic the similar API, as currently the debounce function is much simpler than what we have in `CKEDITOR.tools.buffers`.

2022-06-20 14:55 UTC, Comandeer commented
> However, in the case of the testing phase, we may get many false-positive results e.g because manual tests will rely on personal tester experience (the high-resolution images will slow down the editor anyway).

WDYT about adding a manual test with two editors – one with the `editorplaceholder` plugin and one without it? This way the developer would be able to compare the performance between them and check if the plugin degrades it. That would allow us to empirically validate if the fix really works.

2022-06-27 09:06 UTC, Comandeer commented
Rebased onto latest `master`.

2022-06-27 15:55 UTC, Comandeer approved these changes
LGTM!

2022-06-27 15:55 UTC, merged