Fix #5158 - restore calculator element if removed
ckeditor/ckeditor4 pull request #5238
Opened 2022-06-09 09:43 UTC by sculpt0r

## What is the purpose of this pull request?

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [X] Unit tests
- [ ] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [X] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
* [#<ISSUE_NUMBER>](https://github.com/ckeditor/ckeditor4/issues/<ISSUE_NUMBER>): Describe the purpose of the pull request in a few simple sentences.
```

## What changes did you make?

*Give an overview…*

## Which issues does your PR resolve?

Closes #5158.

2022-06-10 12:41 UTC, jacekbogdanski requested changes

2022-06-10 12:41 UTC, jacekbogdanski commented on core/tools.js
> +				if ( calculator.isDetached() ) {
I think that at this point we can assume that calculator has been somehow manipulated without our supervision. So, we can assume that it's broken and should be re-created instead.

2022-06-21 11:59 UTC, sculpt0r commented
Rebased on the newest master.

2022-06-21 12:07 UTC, sculpt0r commented
@jacekbogdanski - ready for another review :)
- The calculator is now recreated also whenever it was removed from the DOM

2022-06-28 07:38 UTC, jacekbogdanski approved these changes
Looks good, just minor issues (I will correct them).

2022-06-28 07:38 UTC, jacekbogdanski commented on tests/core/tools.js
> +			assert.areSame( result, 10, 'calculator was not properly attached to DOM.' );
The step comparing the first result and the second one is unnecessary. Also, the proper order of assertion method parameters is _expected_, _actual_.

2022-06-28 07:52 UTC, merged