Fix: dialog validators compositions incorrectly join results
ckeditor/ckeditor4 pull request #5248
Opened 2022-06-22 07:34 UTC by sculpt0r

## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [X] Unit tests
- [ ] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [X] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
* [#4449](https://github.com/ckeditor/ckeditor4/issues/4449): Fix: [dialog.validate#functions](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dialog_validate.html#method-functions) correctly returns value if any composed validator failed.
```

## What changes did you make?

*Give an overview…*

According to the [community suggestion](https://github.com/ckeditor/ckeditor4/issues/4449#issuecomment-750873496) - I used a strict comparison for the composed validator's return values.

Created a separate test file for the composition validator. Added a test case as proof of bug (marked with issue reference). Also, added other test cases - since I can not find any tests for this feature.

According to tests cases: please notice that in the case of `CKEDITOR.VALIDATOR_OR` we do not require to call all passed validators. They are called right now - but the more important thing is the result in this case.

Tests still use the 'hack' with `getValue` setup (the same as other tests). We will get rid of that after #4473 .

Side note:
We do not validate the message that is returned from the single validator. So it is possible to use the API in a funky-incorrect way:
```js
var incorrectValidator = CKEDITOR.dialog.validate.notEmpty( true );
```
Such validator returns true in case of failed validation - which will be also invalid as a part of the composition - but I guess this is a matter of proper API usage - not a bug?

## Which issues does your PR resolve?

Closes #4449 .

2022-06-29 11:29 UTC, KarolDawidziuk requested changes
Hi, @sculpt0r 
I've made an early review of Your PR.

Overall, everything looks good and the issue with truthy values is gone. There are some tiny things that can be improved. Please see my inline comments.

2022-06-30 06:51 UTC, sculpt0r commented on plugins/dialog/plugin.js
> +						isValid = functions[ i ]( value ) === true;
> Is there a reason we want to declare isValid outside of a for loop? 

I wanted to merge the variable declaration with the `passed` variable declaration. But I'll correct that. Also, I renamed it.

2022-06-30 07:16 UTC, sculpt0r commented
@KarolDawidziuk - ready for another review

All your previous comments are applied.

2022-06-30 09:32 UTC, KarolDawidziuk requested changes
Thanks, @sculpt0r for the improvements.

Now it looks clearer but I think that we still we can improve it. Please see my inline comments.

2022-07-04 11:51 UTC, sculpt0r commented
Rebased on the newest master.

2022-07-04 12:18 UTC, sculpt0r commented
@KarolDawidziuk - ready for another review

I only applied https://github.com/ckeditor/ckeditor4/pull/5248#discussion_r910809651 suggestion. Indeed lack of curly braces sometimes might generate issues.

There is a redundancy in comparison `relation` variable with the const - however:
- it is hard to find a good enough name for such a relation that will be easily understandable, so `realtion === CKEDITOR.VALIDATE_AND` is in my opinion the most understandable.
- it appears only two times in closed scope - and the suggestion decreases this number to only one. IMO not that much in terms of above ☝️

I hope you understand the choice :)

2022-07-04 19:26 UTC, KarolDawidziuk approved these changes
LGTM! 🎉 

This was a part of an early review. In the next step, PR will be checked again by a more experienced developer.

2022-07-06 08:12 UTC, jacekbogdanski approved these changes
Looks good. I've simplified tests a bit.

2022-07-06 09:16 UTC, merged