Add enter key support for `Find&Replace`
ckeditor/ckeditor4 pull request #5262
Opened 2022-07-07 08:15 UTC by KarolDawidziuk

## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [x] Unit tests
- [x] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [x] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
* [#5022](https://github.com/ckeditor/ckeditor4/issues/5022): Fixed: [Find/Replace](https://ckeditor.com/cke4/addon/find) Find and replace does not respond to the `Enter` key.
```

## What changes did you make?

Enter key not triggered find or replace because dialogs by default contain [handling only to dialog `OK` button](https://github.com/ckeditor/ckeditor4/blob/t/5022/plugins/dialog/plugin.js#L545-L554). To fix this I added `onKeyEvent` to the dialog inputs with executing `find` or `replace` method on current finder.

## Which issues does your PR resolve?

Closes #5022.

2022-07-07 13:14 UTC, jacekbogdanski requested changes
There is an issue with a replace handler as the match previously found by find is dismissed introducing inconsistency. E.g.

1. Find "bar" 2x.
2. Replace "bar" with "foo".

**Expected** The second "bar" occurrence found by the find method is replaced.
**Actual** Searching is restarted and the first "bar" occurrence is replaced.

https://user-images.githubusercontent.com/10279586/177781928-f5d71247-bc1b-4217-ba47-f254af51a76c.mov

2022-07-07 13:14 UTC, jacekbogdanski commented on plugins/find/dialogs/find.js
> +		function execFindOrReplace( dialog, type ) {
I would split find and replace to different functions for readability and have dedicated `execFind` / `exedReplace` functions.

2022-07-07 13:14 UTC, jacekbogdanski commented on plugins/find/dialogs/find.js
> +							if ( keystroke !== 13 ) {
It would be good to avoid magic numbers and extract `13` to constant (like you did in the unit test).

2022-07-07 14:08 UTC, KarolDawidziuk commented
Thanks, @jacekbogdanski for the review. 

I applied improvements from your comments and PR is ready for another check.

Unfortunately, for some reason, I was not able to reproduce the issue from the video. 🤔 Tried with a different approach.

2022-07-11 14:28 UTC, jacekbogdanski approved these changes

2022-07-11 14:29 UTC, merged