Add support for array in the `config.removeButtons`
ckeditor/ckeditor4 pull request #5302
Opened 2022-08-01 15:23 UTC by Comandeer

## What is the purpose of this pull request?

New feature

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [x] Unit tests
- [x] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [x] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
* [#5122](https://github.com/ckeditor/ckeditor4/issues/5122): Added ability to provide a list of buttons as an array to the [`config.removeButtons`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-removeButtons) config variable.
```

## What changes did you make?

I've added a simple helper that calls `split()` on the `config.removeButtons` variable only if it's a string. Otherwise, the original value is returned.

## Which issues does your PR resolve?

Closes #5122.

2022-08-05 11:08 UTC, KarolDawidziuk requested changes
Hi @Comandeer 

I've made an early review of your PR.
Overall everything is good and removing buttons by passing an array works great. Good job!

There are a few things that can be improved in code style. Please see my inline comments.

2022-08-08 15:55 UTC, Comandeer commented on plugins/toolbar/plugin.js
> +		function getRemoveButtonsConfig( config ) {
Sounds reasonable, I'll change it to `getRemoveButtons()`.

2022-08-08 15:57 UTC, Comandeer commented
Applied the proposed code style fixes and rebased onto the latest `master`.

2022-08-09 05:40 UTC, KarolDawidziuk approved these changes
Thank you @Comandeer for the improvements.
LGTM! 🎉 

It was a part of an early review. In the next step, this PR will be checked again by a more experienced developer.

2022-08-09 06:45 UTC, jacekbogdanski approved these changes

2022-08-09 06:45 UTC, jacekbogdanski commented on plugins/toolbar/plugin.js
> + * From version 4.20.0 you can also pass an array of button names:
```suggestion
 * Since version 4.20.0 you can also pass an array of button names:
```

2022-08-09 06:47 UTC, merged