Allow using custom styles from config.contentsCss for Colorplugin
ckeditor/ckeditor4 pull request #5353
Opened 2022-10-18 10:12 UTC by mihilion

## What is the purpose of this pull request?

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [ ] Unit tests
- [ ] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [ ] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
* [#<ISSUE_NUMBER>](https://github.com/ckeditor/ckeditor4/issues/<ISSUE_NUMBER>): Describe the purpose of the pull request in a few simple sentences.
```

## What changes did you make?

*Give an overview…*

## Which issues does your PR resolve?

Closes #<ISSUE_NUMBER>.

2022-10-20 08:46 UTC, KrzysztofBogdan commented
That update would be helpful for us! :heart:

2022-10-21 13:54 UTC, Comandeer requested changes
@mihilion, thanks for the PR! Could you add missing information from the pull request template to describe the purpose of your PR? I suppose it's fixing #5352?

Additionally, could you add some tests for your changes? There are [instructions in our docs](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests) for creating new tests. Probably a manual test will be enough for such a change.

2022-10-28 10:21 UTC, mihilion commented
@Comandeer I have added missing information and manual test.

2022-11-02 16:46 UTC, Comandeer requested changes
@mihilion, please see: [https://github.com/ckeditor/ckeditor4/issues/5352#issuecomment-1300872876](https://github.com/ckeditor/ckeditor4/issues/5352#issuecomment-1300872876)

The `config.contentsCss` should be replaced by the introduction of the new config variable, `config.colorButton_css` that will take the array of stylesheets. Could you make that change?

2022-11-18 09:18 UTC, mihilion commented
I'm back after a break, I have introduced new property as requested.

2022-11-29 14:14 UTC, Comandeer requested changes
@mihilion, thanks! The code looks good, I have left only one inline note. Could you look into it?

2022-12-04 16:45 UTC, mihilion commented on plugins/colorbutton/plugin.js
> + * 		config.colorButton_css = ['span.cke_colorbox { border-radius: 50%; }']
I have updated documentation and test case. I have combined both approaches in a single test case, to show that they can even be mixed.

2022-12-20 09:01 UTC, jacekbogdanski approved these changes
Thank you @mihilion for your contribution! I've changed a bit your proposition to match the existing API of https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-contextmenu_contentsCss and corrected some minor issues.

To credit your work I mentioned you in the changelog 🙇🏻

2022-12-20 09:12 UTC, merged