Fix "Cannot read property 'attributes' of null"
ckeditor/ckeditor4 pull request #5400
Opened 2023-01-09 07:53 UTC by glen-84

## What is the purpose of this pull request?

## Does your PR contain necessary tests?

No, it's a minor change. Let me know if this is necessary.

### This PR contains

- [ ] Unit tests
- [ ] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [x] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
* [#698](https://github.com/ckeditor/ckeditor4/issues/698): Fix "Cannot read property 'attributes' of null".
```

## What changes did you make?

Checked that `element` and `widgetElement` are non-null before accessing `attributes`.

## Which issues does your PR resolve?

Closes #698.

2023-01-11 17:21 UTC, Comandeer requested changes
Hi, @glen-84! Thanks for your contribution.

As all changes to the CKEditor 4 codebase require tests, can I ask you to add some? We have a [guide describing our test environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html).

Additionally, the fix does not seem to resolve all issues around switching to the source mode. The original issue is fixed but when I tried the [original reproduction](https://jsfiddle.net/a6xrqx2u/) with your fix, I got another error:

```javascript
node.js:45 Uncaught TypeError: Cannot set properties of null (setting 'previous')
    at CKEDITOR.htmlParser.element.replaceWith (node.js:45:30)
    at Editor.<anonymous> (plugin.js:3119:18)
    at Editor.listenerFirer (event.js:169:34)
    at CKEDITOR.event.fire (event.js:313:36)
    at CKEDITOR.editor.fire (editor_basic.js:24:40)
    at CKEDITOR.htmlDataProcessor.toDataFormat (htmldataprocessor.js:301:23)
    at $.getData (plugin.js:623:34)
    at $.<anonymous> (editable.js:839:22)
    at Editor.listenerFirer (event.js:169:34)
    at CKEDITOR.event.fire (event.js:313:36)
```

Could you check if it can be easily fixed?

2023-01-15 15:33 UTC, glen-84 commented
@Comandeer

I wrote this test:

```js
/* bender-tags: widget */

( function() {
	'use strict';

	CKEDITOR.dtd.$editable.span = 1;

	CKEDITOR.plugins.add( 'spanwidget', {
		requires: 'widget',
		init: function ( editor )	{
			editor.widgets.add( 'spanwidget', {
				editables: {
					content: {
						selector: 'span'
					}
				},
				upcast: function ( element ) {
					return element.name == 'span';
				}
			});
		}
	});

	bender.editor = {
		creator: 'replace',
		config: {
			allowedContent: true,
			extraPlugins: 'basicstyles,embed,sourcearea,spanwidget'
		}
	};

	bender.test( {
		'Fix #698': function() {
			var tc = this;

			tc.editor.setData( '<strong><span>lorem</span></strong>', function() {
				tc.resume( function() {
					tc.editor.focus();

					var textNode = tc.editor.editable().findOne( 'span' ).getFirst().getFirst();

					// Select the `m`.
					var rng = tc.editor.createRange();
					rng.setStart( textNode, 4 );
					rng.setEnd( textNode, 5 );
					tc.editor.getSelection().selectRanges( [ rng ] );

					tc.editor.execCommand( 'bold' )

					tc.editor.setMode( 'source' );

					assert.isTrue( true ); // Assert no errors?
				}, 100 );
			} );

			tc.wait();
		}
	} );

} )();
```

But it triggers the error that you mentioned, and if I add `if ( !widgetElement ) continue;` in `setupWidgetsLifecycleEnd`, the source editor shows HTML from CKE:

```html
<p><strong><span>lorem</span></strong><strong><span tabindex="-1" contenteditable="false" role="region" aria-label="span widget"><span style="background:rgba(220,220,220,0.5);background-image:url(http://localhost:1030/apps/ckeditor/plugins/widget/images/handle.png);display:none;"><img src="data:image/gif;base64,R0lGODlhAQABAPABAP///wAAACH5BAEKAAAALAAAAAABAAEAAAICRAEAOw==" width="15" title="Click and drag to move" height="15" role="presentation" draggable="true" /></span></span></strong></p>
```

I'm really out of my depth here. If you're able to assist with finishing this up, I'd appreciate that.

2023-01-23 14:48 UTC, Comandeer commented
@glen-84, I've added your test (slightly modified to better fit with the style with our newer tests but the overall logic is left untouched) alongside a manual one.

The `setupWidgetsLifecycleEnd()` was a correct place to apply a fix. Although it's probably better to [simply remove the widget](eb14c12b4b09a682759a1076618f26c3946b591167ad6cbed255dR3119-R3128) if there is no `retElement` at the end of this function. Especially as applying bold to the last letter in the `span` causes the widget to be duplicated.

I see that you also added an additional check to the `embedsemantic` plugin. Could you explain why is it needed (or describe a case when the issue occurs in that plugin)?

2023-01-25 11:24 UTC, Comandeer commented
> My plugin uses a span, not a div.

That's probably the reason why the issue appears in your plugin. There is no official support for inline editables in CKEditor 4 so some things could work incorrectly.

2023-01-25 11:46 UTC, Comandeer approved these changes
LGTM! Thanks for your contribution, @glen-84!

However, as I've also added some changes to the PR, I'll ask @KarolDawidziuk to have a second look at it.

2023-01-27 09:16 UTC, KarolDawidziuk requested changes
Thanks for your improvements.

The main issue with throwing an error is solved, good job! 
There are some code-style things(mostly nitpicks) that we can improve. Please see my inline comments.

Also, there is an issue with inserting an additional empty `<strong>` element in the iframe-based editor when we switch to the source mode, but this is not in the scope of this PR.
Let's extract this as a follow-up and after you apply changes from inline comments PR will be ready to merge.

2023-01-27 09:16 UTC, KarolDawidziuk commented on tests/plugins/widget/manual/inlineeditable.md
> +	**Unexpected** There is an error in the console and editor is not switched to the editing mode.
Based on our [code style](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md#31-manual-tests) this additional indentation is unnecessary, let's remove this.
```suggestion
**Expected** Editor is switched to the source mode.

**Unexpected** There is an error in the console and editor is not switched to the source mode.

1. Switch back to the editing mode.

**Expected** Editor is switched to the editing mode.

**Unexpected** There is an error in the console and editor is not switched to the editing mode.
```

2023-01-27 09:16 UTC, KarolDawidziuk commented on tests/plugins/widget/manual/inlineeditable.md
> +1. Click the "Bold" toolbar button.
```suggestion
1. Click the `Bold` toolbar button.
```

2023-01-27 09:16 UTC, KarolDawidziuk commented on tests/plugins/widget/manual/inlineeditable.md
> +@bender-tags: widget, bug, 698, 4.21.0
Based on our [code style](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md#31-manual-tests) let's use a correct tag order:
```suggestion
@bender-tags: 4.21.0, bug, 698, widget
```

2023-01-27 19:14 UTC, glen-84 commented on plugins/widget/plugin.js
>  							delete widgetElement.attributes[ 'data-widget' ];
This is existing code, unrelated to this PR. 🙂

2023-01-27 19:17 UTC, glen-84 commented
I'll leave the other suggestions for @Comandeer, since they are related to his changes.

2023-02-06 08:55 UTC, Comandeer commented
@KarolDawidziuk, thx for the review. I've applied your suggestions and PR is ready for another one.

2023-02-06 09:20 UTC, KarolDawidziuk approved these changes
LGTM! 🎉

2023-02-06 09:23 UTC, merged

2023-02-06 09:23 UTC, Comandeer commented
Merged. @glen-84, thanks once more for your contribution!