Prevent using `document.domain` by Firefox in the `preview` plugin
ckeditor/ckeditor4 pull request #5439
Opened 2023-03-06 08:03 UTC by KarolDawidziuk

## What is the purpose of this pull request?

Task

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [ ] Unit tests
- [ ] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [x] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
* [#5412](https://github.com/ckeditor/ckeditor4/issues/5412): Prevent using `document.domain` by Firefox in the `preview` plugin.
```

## What changes did you make?

In the previous PR with fixing print on Firefox, we [allowed using document.domain](https://github.com/ckeditor/ckeditor4/pull/4813/files#diff-36cb2ca37dc3086bbe191b661d4f8923ff5872b765b8d537439a568da622580aR216) to properly open the preview before print while using the editor from CDN. Looks like FF fixed this and we can remove it.
Additionally, we could simplify the code more by removing [fix for creating links to anchor](https://dev.ckeditor.com/ticket/9047).

## Which issues does your PR resolve?

Closes #5412.

2023-03-21 12:17 UTC, Comandeer requested changes
The changes seem to work properly, there are some more opportunities to simplify the code and we should probably update our tests a bit. Please, see my inline comments for more info.

2023-03-28 07:12 UTC, KarolDawidziuk commented on plugins/preview/plugin.js
> -		// #(4444)
I assume you were referring to #4444?

2023-03-28 07:20 UTC, KarolDawidziuk commented
Thanks, @Comandeer for your input. I've applied changes mentioned in your comments and PR is ready for another review.

2023-04-11 09:55 UTC, Comandeer commented on plugins/preview/plugin.js
> -		// #(4444)
Yes 🙈

2023-04-11 11:35 UTC, Comandeer approved these changes
LGTM!

2023-04-11 11:36 UTC, merged