Fix incorrect selection handling in the Rich Combos
ckeditor/ckeditor4 pull request #5478
Opened 2023-05-12 16:02 UTC by Comandeer

## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [x] Unit tests
- [x] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [x] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
* [#5437](https://github.com/ckeditor/ckeditor4/issues/5437): Fix: incorrect indication of selected items in comboboxes.
```

## What changes did you make?

I've discovered that we have a whole logic to apply the `[aria-selected]` attribute in place. However, the selected item was unmarked upon each opening of the combobox due to an [incorrectly applied fix](https://github.com/ckeditor/ckeditor4/commit/61a6108#diff-f135dd6497a04478a9efbb561d78b60189163d378f53188ae4c3ba0884e6f671R183-R189) to an [old accessibility issue](https://dev.ckeditor.com/ticket/16804). It was supposed to ensure that after opening the context menu, the first item will be focused. However, as comboboxes are not context menus and their [keyboard interaction pattern](https://www.w3.org/WAI/ARIA/apg/patterns/listbox/#keyboardinteraction) is quite different, I simply removed the old fix.

As a bonus, we now have also correct styling of the selected items in comboboxes 🎉 

## Which issues does your PR resolve?

Closes #5437.

2023-06-01 13:34 UTC, Comandeer commented
As the "Styles" combo seems to work well even without the fix, I've updated tests to use the "Font" one. Additionally I've rebased the PR onto the latest `master`.

2023-06-01 22:07 UTC, KarolDawidziuk requested changes
Hi @Comandeer 

Good job on removing the unnecessary method, therefore, improving selection handling in the Rich Combos. 👏 

There is one place that we must update as this method no longer exist.
https://github.com/ckeditor/ckeditor4/blob/master/plugins/floatpanel/plugin.js#L427-L430

This shortened if statement is no longer valid and we can simplify it to just:

```JS
if ( CKEDITOR.env.ie ) {
	CKEDITOR.tools.setTimeout( function() {
		block._.markFirstDisplayed();
	}, 0 );
} else {
	block._.markFirstDisplayed();
}
```

Could you update it, please?

2023-06-19 11:25 UTC, Comandeer commented
After F2F with @KarolDawidziuk we decided to keep the conditional in the same shape to ensure the highest backward compatibility with potential custom marking logic for panels.

2023-06-19 21:49 UTC, KarolDawidziuk approved these changes
LGTM! 🎉

2023-06-19 21:49 UTC, merged